name: Cleanup Branches

on:
  workflow_dispatch: # Allows you to trigger this manually

jobs:
  cleanup_branches:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install jq and GitHub CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y jq
        sudo apt-get install -y gh

    - name: List branches without recent commits
      env:
        REPO: ${{ github.repository }}
        GH_TOKEN: ${{ github.token }}
      id: list_branches
      run: |
        # Set the cutoff date to one year ago
        cutoff_date=$(date -d '1 year ago' +%Y-%m-%d)
        
        # Branches to skip
        skip_branches=("main" "master" "develop" "qa" "staging")

        # Prepare the list of branches to delete
        branches_to_delete=()

        # Get all branches
        all_branches=$(gh repo view --json refs --jq '.refs[] | select(.isDefault == false) | .name' | sed 's!refs/heads/!!')

        for branch in $all_branches; do
          # Check if the branch is in the skip list
          if [[ " ${skip_branches[@]} " =~ " ${branch} " ]]; then
            continue
          fi

          # Get the last commit date for the branch
          last_commit_date=$(gh api repos/:owner/:repo/commits?sha=$branch --jq '.[-1].commit.committer.date')

          # Compare dates
          if [[ "$last_commit_date" < "$cutoff_date" ]]; then
            branches_to_delete+=($branch)
          fi
        done

        # Output the list to a file
        if [ ${#branches_to_delete[@]} -gt 0 ]; then
          printf "%s\n" "${branches_to_delete[@]}" > branches_to_delete.txt
        else
          echo "No branches to delete." > branches_to_delete.txt
        fi

    - name: Upload branches to delete as artifact
      uses: actions/upload-artifact@v4
      with:
        name: branches-to-delete
        path: branches_to_delete.txt
    
    # Uncomment the following step if you want to delete the branches automatically
    # - name: Delete branches
    #   run: |
    #     for branch in "${branches_to_delete[@]}"; do
    #       git branch -D "$branch"
    #     done