# Github workflow to remove branches older than 1 year
name: Delete Old Branches

permissions:
  contents: write

on:
  workflow_dispatch:  # Allows manual triggering if needed

jobs:
  delete-old-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install jq and GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          sudo apt-get install -y gh

      - name: Prepare list of branches to delete
        id: prepare
        env:
          REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
        run: |
          # Get the date 12 months ago in ISO format
          ONE_YEAR_AGO=$(date -d '12 months ago' +%Y-%m-%dT%H:%M:%SZ)
          BRANCHES_TO_DELETE=""

          # Fetch all branches and filter by last commit date
          BRANCHES_TO_DELETE=$(gh api -X GET "repos/$REPO/branches" --paginate \
            | jq -r --arg date "$ONE_YEAR_AGO" '.[] | select(.commit.commit.author.date < $date) | .name' \
            | while read branch; do
                # Skip protected branches
                if [[ "$branch" == "main" || "$branch" == "master" || "$branch" == "develop" || "$branch" == "qa" || "$branch" == "staging" ]]; then
                  echo "Skipping protected branch: $branch"
                  continue
                fi
                # Add branch to the list to delete
                echo "$branch"
              done)

          # Save list to a file
          echo "$BRANCHES_TO_DELETE" > branches_to_delete.txt
          echo "::set-output name=branches::$BRANCHES_TO_DELETE"
          
      - name: Upload branches to delete file
        uses: actions/upload-artifact@v4
        with:
            name: branches-to-delete
            path: branches_to_delete.txt
