name: Clean up old branches

permission: write

on:
  workflow_dispatch:

jobs:
  list_old_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List branches older than 1 year
        id: list_old_branches
        run: |
          # Exclude specific branches
          excluded_branches="main master develop qa staging"

          # List branches with no commits in the past year, excluding specified branches
          branches=$(git for-each-ref --format="%(refname:short)" refs/heads/ |
            while read branch; do
              if [[ ! " $excluded_branches " =~ " $branch " ]]; then
                if [ $(git log -1 --since="1 year ago" --pretty=format:"%h" $branch | wc -l) -eq 0 ]; then
                  echo $branch
                fi
              fi
            done)

          # Save branch list to file
          echo "$branches" > branches_to_delete.txt

          # Set output for the branches to be deleted
          echo "::set-output name=branches::$branches"

      - name: Upload branches to delete as artifact
        uses: actions/upload-artifact@v4
        with:
          name: branches_to_delete
          path: branches_to_delete.txt

  delete_old_branches:
    runs-on: ubuntu-latest
    needs: list_old_branches
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: branches_to_delete
          path: ./

      - name: Delete old branches
        run: |
          # Read the branches from the file
          while IFS= read -r branch; do
            git push origin --delete "$branch"
          done < branches_to_delete.txt