# Github workflow to remove branches older than 1 year
name: Delete Old Branches

permissions:
  contents: write

on:
  workflow_dispatch:  # Allows manual triggering if needed

jobs:
  delete-old-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install jq and GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          sudo apt-get install -y gh
      - name: Delete branches older than 24 months
        env:
          REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
        run: |
          # Get the date 24 months ago in ISO format
          TWO_YEAR_AGO=$(date -d '24 months ago' +%Y-%m-%dT%H:%M:%SZ)
          echo "Deleting branches before: $TWO_YEAR_AGO"
          # Fetch all branches and filter by last commit date
          gh api -X GET "repos/$REPO/branches" --paginate \
            | jq -r --arg date "$TWO_YEAR_AGO" '.[] | select(.commit.commit.author.date < $date) | .name' \
            | while read branch; do
                # Skip protected branches
                if [[ "$branch" == "main" || "$branch" == "master" || "$branch" == "develop" || "$branch" == "qa" || "$branch" == "staging" ]]; then
                  echo "Skipping protected branch: $branch"
                  continue
                fi
                # Delete the branch
                echo "Deleting branch: $branch"
                gh api -X DELETE "repos/$REPO/git/refs/heads/$branch"
              done